ci dispatch logic

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,6 +4,8 @@ on:
   pull_request:
     branches:
       - master
+  repository_dispatch:
+    types: [cloud-init-status, docker-container-status]  
 
 jobs:
   build-and-push:
@@ -28,13 +30,14 @@ jobs:
           IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/kardanai:latest"
           docker push $IMAGE_NAME
     
-  deploy-and-run:
+  deploy:
     name: Deploy to DigitalOcean and Collect Logs
     #needs: build-and-push
     runs-on: ubuntu-latest
     env:
       DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+      FLOW_CONTROL_GITHUB_TOKEN: ${{ secrets.FLOW_CONTROL_GITHUB_TOKEN }}
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -55,37 +58,55 @@ jobs:
 
           cd deploy && bash do-create-droplet.sh
 
-        # Если нужно будет более одного хоста, логику надо переделать вместо docker ip
-        # использовать droplet id
-      - name: Wait for Docker Container to Finish and Collect Logs
+  cloud-init-status:
+    name: Check Cloud Init Status 
+    runs-on: ubuntu-latest
+    needs: deploy
+    if: github.event_name == 'repository_dispatch' && github.event.action == 'cloud-init-status'
+    steps:
+      - name: Get Cloud Init Status
         run: |
-          DROPLET_IP=$(cat droplet_ip.txt)
-          
-          echo "Adding SSH key to agent"
-          mkdir -p ~/.ssh
-          echo "${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-          
-          # проверим готовность провиженинга дроплета
-          bash deploy/check_startup.sh $DROPLET_IP
-            
-          echo "Waiting for container to finish..."
-          while ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "docker ps --filter 'name=train' --format '{{.Names}}'" | grep -q "train"; do
-            echo "Container is still running..."
-            sleep 30
-          done
+          if [ "${{ github.event.client_payload.status }}" == "ready" ]; then
+            echo "Cloud init completed successfully"
+          else
+            echo "Cloud init failed"
+            exit 1
+          fi
 
-          echo "Container finished, collecting logs..."
-          ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "docker logs train" > container_logs.txt
+  docker-container-status:
+    name: Check Docker Container Status and Collect Logs
+    runs-on: ubuntu-latest 
+    needs: cloud-init-status
+    if: github.event_name == 'repository_dispatch' && github.event.action == 'docker-container-status'
+    steps:
+      - name: Checkout Repository 
+        uses: actions/checkout@v4
+
+      - name: Get Docker Container Status
+        run: |
+          if [ "${{ github.event.client_payload.status }}" == "completed" ]; then
+            echo "Docker container completed successfully"
+          else
+            echo "Docker container failed"
+            exit 1
+          fi
 
       - name: Save Logs as Artifact
         uses: actions/upload-artifact@v4
         with:
           name: container-logs
-          path: container_logs.txt
-
+          path: "${{ github.event.client_payload.log_path }}"
+  
+  cleanup:
+    name: Delete Droplet
+    needs: docker-container-status
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        
       - name: Delete Droplet
         run: |
           DROPLET_IP=$(cat droplet_ip.txt)
           doctl compute droplet delete "$DROPLET_IP" --force
-  
